package com.example.adaptivetestingbackend.service.ai.client

import com.example.adaptivetestingbackend.ai.client.AiGenerateTextRequest
import com.example.adaptivetestingbackend.ai.client.AiGenerateTextResponse
import com.example.adaptivetestingbackend.ai.client.AiTextGenerationClient
import org.slf4j.LoggerFactory
import java.util.UUID

class StubAiTextGenerationClient : AiTextGenerationClient {

    private val logger = LoggerFactory.getLogger(javaClass)

    override fun generateText(request: AiGenerateTextRequest): AiGenerateTextResponse {
        logger.info(
            "AI operation={} correlationId={} providerMode={} result=success",
            request.operation,
            request.correlationId,
            providerMode(),
        )

        return AiGenerateTextResponse(
            content = deterministicContent(request.operation),
            provider = providerMode(),
            requestId = "stub-${UUID.nameUUIDFromBytes(request.prompt.toByteArray())}",
            stub = true,
        )
    }

    override fun providerMode(): String = "stub"

    private fun deterministicContent(operation: String): String {
        return when (operation) {
            "custom-test-draft" ->
                """
                {
                  "title": "Demo soft-skills pulse check",
                  "description": "Deterministic skeleton draft generated by stub AI provider.",
                  "questions": [
                    {
                      "text": "How do you usually react when requirements change late?",
                      "options": ["Calmly reprioritize", "Need extra guidance", "Escalate immediately", "Postpone changes"]
                    },
                    {
                      "text": "Which collaboration format is most effective for you?",
                      "options": ["Short sync calls", "Written async updates", "Pair sessions", "Independent work"]
                    }
                  ]
                }
                """.trimIndent()

            "custom-test-interpretation" ->
                """
                {
                  "summary": "The participant demonstrates stable communication preferences and adaptive behavior.",
                  "observations": [
                    "Answers are consistent across related questions.",
                    "There is a clear preference for structured collaboration."
                  ],
                  "recommendations": [
                    "Use short weekly reflection checkpoints.",
                    "Provide explicit success criteria before starting tasks."
                  ],
                  "disclaimer": "Demo AI interpretation. Validate with a qualified specialist before making high-stakes decisions."
                }
                """.trimIndent()

            else -> "{\"message\":\"Unsupported operation for stub\"}"
        }
    }
}
